### ISSUE TITLE
파이어폭스 애드온 출시 문의

### ISSUE THREAD

**Issue by WDever** [JaeYeopHan/pretty-octo#5]
## Description
크롬에서는 잘 사용하고 있었습니다만 파이어폭스 디벨로퍼 에디션으로 주사용 브라우저를 바꾸고 난 후에 사용하지 못해서 좀 아쉽더라구요. 혹시 파이어폭스 애드온으로는 출시하실 의향이 없으신가요?
### Request Feature
파이어폭스 애드온 출시 의향이 궁금합니다.

**Comment by jbee37142** [comment]
네에 시간을 내보겠습니다 🙏

**Comment by WDever** [comment]
생각해주셔서 감사합니다 ☺️
